// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUvzpz2wbS1Mf92nKWm_Xxt2vEZwLsK8',
    appId: '1:471395524735:web:52cfc5d046521be385df4a',
    messagingSenderId: '471395524735',
    projectId: 'tistory-fcm-2605',
    authDomain: 'tistory-fcm-2605.firebaseapp.com',
    storageBucket: 'tistory-fcm-2605.firebasestorage.app',
    measurementId: 'G-DZFP0J014T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYkkaI-ftXcU8gHpeL6RRZcomz_t7fKA',
    appId: '1:471395524735:android:79f4ee2c683a384385df4a',
    messagingSenderId: '471395524735',
    projectId: 'tistory-fcm-2605',
    storageBucket: 'tistory-fcm-2605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5_GKv6BZUfUKgj6gWY2VvzuAWcRej0A',
    appId: '1:471395524735:ios:418991b14372994385df4a',
    messagingSenderId: '471395524735',
    projectId: 'tistory-fcm-2605',
    storageBucket: 'tistory-fcm-2605.firebasestorage.app',
    iosBundleId: 'com.example.fcmFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5_GKv6BZUfUKgj6gWY2VvzuAWcRej0A',
    appId: '1:471395524735:ios:418991b14372994385df4a',
    messagingSenderId: '471395524735',
    projectId: 'tistory-fcm-2605',
    storageBucket: 'tistory-fcm-2605.firebasestorage.app',
    iosBundleId: 'com.example.fcmFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJUvzpz2wbS1Mf92nKWm_Xxt2vEZwLsK8',
    appId: '1:471395524735:web:8cc489c76c2467fb85df4a',
    messagingSenderId: '471395524735',
    projectId: 'tistory-fcm-2605',
    authDomain: 'tistory-fcm-2605.firebaseapp.com',
    storageBucket: 'tistory-fcm-2605.firebasestorage.app',
    measurementId: 'G-NTD199W1HW',
  );
}
